language: node_js
node_js:
  - 8
before_script:
  - npm install @11ty/eleventy -g
script: eleventy
deploy:
  provider: pages
  on:
    branch: develop
  local-dir: dist # Copy the generated files to the `master` branch instead of `gh-pages`.
  target-branch: master
  github-token: $GITHUB_TOKEN # Set in travis-ci.org dashboard, marked secure.
  committer_from_gh: true
  keep-history: true
  skip-cleanup: true
